sudo: required
services:
  - docker

before_install:
  - docker build -t gaeshi2/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run gaeshi2/react-test npm test -- --coverage

after_success:
  - docker build -t gaeshi2/multi-client ./client
  - docker build -t gaeshi2/multi-nginx ./nginx
  - docker build -t gaeshi2/multi-server ./server
  - docker build -t gaeshi2/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push gaeshi2/multi-client
  - docker push gaeshi2/multi-nginx
  - docker push gaeshi2/multi-server
  - docker push gaeshi2/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-350583070229
  bucket_path: docker-multi
  on:
    branch:  master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secret: $AWS_SECRET_KEY